In [2]:
import numpy as np
import torch

In [3]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [4]:
# 行数
print(x.size(0))

4


In [5]:
# 列数
print(x.size(1))

3


In [6]:
# tensor张量 和 标量 直接相加
v = torch.tensor([1,2,3])
b = 1

print(v + b)

tensor([2, 3, 4])


In [7]:
# 矩阵 和 行向量 直接相加
print(x + v)

tensor([[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12],
        [11, 13, 15]])


In [21]:
# .mean()用于 张量tensor
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype=torch.float32)
result = x.mean()
print(result)

tensor(6.5000)


In [3]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[2,4],[5,6]])

print(torch.mm(a,b))
print(a.mm(b))

tensor([[12, 16],
        [26, 36]])
tensor([[12, 16],
        [26, 36]])


In [6]:
print(a)
a.sum(0)

tensor([[1, 2],
        [3, 4]])


tensor([4, 6])