In [2]:
import torch

In [3]:
x = torch.tensor([[1,0],[1,1],[0,0],[0,1]])
h = torch.randn(size=(4,256))

In [4]:
print(x)

tensor([[1, 0],
        [1, 1],
        [0, 0],
        [0, 1]])


In [5]:
print(h)

tensor([[ 0.0155,  0.2085, -0.2351,  ..., -0.6736, -0.7461, -0.7101],
        [-0.1683, -0.4510,  1.3794,  ...,  0.1393,  0.4831,  0.9808],
        [ 1.8042,  1.3426, -0.1463,  ..., -1.4823, -1.6275,  0.4678],
        [ 0.2968, -1.0739,  0.7831,  ..., -0.7338,  0.1386, -1.9585]])


In [6]:
combine = torch.cat((x,h), dim=-1)

In [7]:
print(combine)

tensor([[ 1.0000,  0.0000,  0.0155,  ..., -0.6736, -0.7461, -0.7101],
        [ 1.0000,  1.0000, -0.1683,  ...,  0.1393,  0.4831,  0.9808],
        [ 0.0000,  0.0000,  1.8042,  ..., -1.4823, -1.6275,  0.4678],
        [ 0.0000,  1.0000,  0.2968,  ..., -0.7338,  0.1386, -1.9585]])


In [16]:
x2 = torch.zeros(size=(4,10,2))
h2 = torch.randn(size=(4,10,256))

In [17]:
print(x2)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])


In [18]:
print(h2)

tensor([[[ 0.0524,  0.8620, -0.7983,  ...,  0.9867, -1.0253, -0.5428],
         [ 1.1762, -0.0646, -0.5105,  ..., -0.6192, -2.0169,  0.3478],
         [-0.1942,  0.5263, -0.5036,  ..., -0.5579, -0.8742, -0.3359],
         ...,
         [ 2.0289,  0.2333,  0.4556,  ...,  1.8044, -0.6517, -0.7787],
         [-1.1339, -0.6307, -0.7684,  ..., -0.2892,  0.6551, -0.7921],
         [ 0.9358, -0.6192, -0.8881,  ...,  0.2800, -0.0699,  0.0135]],

        [[-1.0424,  0.5171, -1.7642,  ..., -0.8112,  1.0943,  1.1740],
         [ 0.3223,  0.2821,  1.7124,  ...,  0.7106,  0.1043, -1.2797],
         [ 0.6133, -1.0515, -0.1476,  ...,  0.6034, -1.5305,  0.2258],
         ...,
         [-0.0804,  0.7664, -0.7639,  ..., -1.8930,  0.5052,  0.8139],
         [ 0.7465,  0.7238, -0.3636,  ...,  2.1908,  0.6761, -0.1346],
         [-1.2214, -1.2979,  1.2694,  ...,  0.4615,  1.0226, -0.8899]],

        [[ 0.0278, -1.8698,  0.0290,  ...,  1.3244,  1.7081,  0.7668],
         [ 0.8461, -1.3549, -0.0469,  ...,  0

In [19]:
combine_2 = torch.cat((x2,h2), dim=-1)

In [20]:
print(combine_2)

tensor([[[ 0.0000,  0.0000,  0.0524,  ...,  0.9867, -1.0253, -0.5428],
         [ 0.0000,  0.0000,  1.1762,  ..., -0.6192, -2.0169,  0.3478],
         [ 0.0000,  0.0000, -0.1942,  ..., -0.5579, -0.8742, -0.3359],
         ...,
         [ 0.0000,  0.0000,  2.0289,  ...,  1.8044, -0.6517, -0.7787],
         [ 0.0000,  0.0000, -1.1339,  ..., -0.2892,  0.6551, -0.7921],
         [ 0.0000,  0.0000,  0.9358,  ...,  0.2800, -0.0699,  0.0135]],

        [[ 0.0000,  0.0000, -1.0424,  ..., -0.8112,  1.0943,  1.1740],
         [ 0.0000,  0.0000,  0.3223,  ...,  0.7106,  0.1043, -1.2797],
         [ 0.0000,  0.0000,  0.6133,  ...,  0.6034, -1.5305,  0.2258],
         ...,
         [ 0.0000,  0.0000, -0.0804,  ..., -1.8930,  0.5052,  0.8139],
         [ 0.0000,  0.0000,  0.7465,  ...,  2.1908,  0.6761, -0.1346],
         [ 0.0000,  0.0000, -1.2214,  ...,  0.4615,  1.0226, -0.8899]],

        [[ 0.0000,  0.0000,  0.0278,  ...,  1.3244,  1.7081,  0.7668],
         [ 0.0000,  0.0000,  0.8461,  ...,  0

In [22]:
data = torch.randn(size=(32,19,10,2))
print(data)

tensor([[[[ 2.9311e+00, -2.5165e-01],
          [ 1.1682e+00,  1.2824e+00],
          [ 6.0708e-01,  4.0157e-01],
          ...,
          [-1.1895e-01,  1.5823e+00],
          [ 5.2990e-01,  1.0151e+00],
          [-1.7498e+00, -4.5011e-01]],

         [[ 8.1242e-01,  9.0319e-02],
          [ 5.1750e-01, -3.7007e-01],
          [ 8.9987e-01, -2.3951e-01],
          ...,
          [-1.1542e+00, -2.3493e-01],
          [ 2.2118e+00, -1.9126e-01],
          [-4.8839e-01, -1.3204e+00]],

         [[ 7.8575e-01, -1.9155e+00],
          [ 5.4796e-01,  3.7750e-01],
          [-2.9233e-01, -1.0091e-01],
          ...,
          [-9.3890e-01,  8.9879e-01],
          [ 1.1692e+00,  1.0128e-01],
          [ 1.9263e+00, -9.6431e-01]],

         ...,

         [[-2.3800e+00,  1.8744e+00],
          [-6.1073e-02,  2.5611e-01],
          [-1.3915e-01,  1.6177e+00],
          ...,
          [-5.2481e-03, -2.4198e+00],
          [-1.3884e-01,  2.1269e-01],
          [-1.6128e-01,  4.8615e-01]],

     

In [23]:
data = data.permute(1,2,0,3)

In [25]:
print(data[0,0].shape)

torch.Size([32, 2])


In [1]:
from torch.nn.utils.rnn import pack_sequence
import torch

# 示例：没有填充的序列列表
seq1 = torch.tensor([1, 2, 3])
seq2 = torch.tensor([4, 5])
seq3 = torch.tensor([6])

# 打包序列
packed = pack_sequence([seq1, seq2, seq3])
print(packed)


PackedSequence(data=tensor([1, 4, 6, 2, 5, 3]), batch_sizes=tensor([3, 2, 1]), sorted_indices=None, unsorted_indices=None)


In [2]:
from torch.nn.utils.rnn import pack_padded_sequence
import torch

# 示例：已填充的序列（不同长度序列的批次）
sequences = torch.tensor([[1, 2, 3], [4, 5, 0], [6, 0, 0]])
lengths = torch.tensor([3, 2, 1])

# 打包填充的序列
packed = pack_padded_sequence(sequences, lengths, batch_first=True, enforce_sorted=False)
print(packed)


PackedSequence(data=tensor([1, 4, 6, 2, 5, 3]), batch_sizes=tensor([3, 2, 1]), sorted_indices=tensor([0, 1, 2]), unsorted_indices=tensor([0, 1, 2]))


In [3]:
from torch.nn.utils.rnn import pad_packed_sequence

# 解包，恢复为填充的序列
padded_seq, lengths = pad_packed_sequence(packed, batch_first=True)
print(padded_seq)
print(lengths)


tensor([[1, 2, 3],
        [4, 5, 0],
        [6, 0, 0]])
tensor([3, 2, 1])
